<?php

/**
 * @file
 * Linked Data Import - Feeds plugins for importing Linked Data content.
 */

define('LD_IMPORT_LABEL_URI', 'http://www.w3.org/2000/01/rdf-schema#label');

/**
* Implements hook_feeds_plugins().
*/
function ld_import_feeds_plugins() {
  $info['LdImportFetcher'] = array(
    'name' => 'Linked Data Import Fetcher',
    'description' => 'Simple text input for list of URIs.',
    'handler' => array(
      'parent' => 'FeedsFetcher',
      'class' => 'LdImportFetcher',
      'file' => 'LdImportFetcher.inc',
      'path' => drupal_get_path('module', 'ld_import') . '/plugins',
    ),
  );
  $info['LdImportParser'] = array(
    'name' => 'Linked Data Import Parser',
    'description' => 'Prepares Linked Data for processing.',
    'handler' => array(
      'parent' => 'FeedsParser',
      'class' => 'LdImportParser',
      'file' => 'LdImportParser.inc',
      'path' => drupal_get_path('module', 'ld_import') . '/plugins',
    ),
  );
  return $info;
}

/**
 * Include the ARC2 library.
 */
function ld_import_include_arc() {
  if (class_exists('ARC2_Class')) {
    return;
  }
  if (module_exists('libraries') && file_exists(libraries_get_path('arc') . '/ARC2.php')) {
    include_once libraries_get_path('arc') . '/ARC2.php';
    ARC2::getResource();
  }
  if (!class_exists('ARC2')) {
    watchdog('ld_import', 'The ARC2 library could not be loaded. ARC2 is required for this module to work. Check the INSTALL file inside the ld_import module folder to find out how ARC can be installed.', WATCHDOG_ERROR);
  }
}
